# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/thefilmproject
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=changethissecretinproductionmustbe256bitslong12345
jwt.expiration=86400000
spring.main.allow-circular-references=true
springdoc.swagger-ui.disable-swagger-default-url=true
cors.allowed.origins=https://stunning-fishstick-9qqgjp5wrg9hp447-3000.app.github.dev
