-- V1: Full initial schema (all tables as of Mar 28 2026)

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    available_for_work boolean NOT NULL,
    bio text,
    city character varying(255),
    country character varying(255),
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL UNIQUE,
    full_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    profile_photo_url character varying(255),
    username character varying(255) UNIQUE,
    email_verified boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id bigint NOT NULL REFERENCES users(id),
    roles character varying(255),
    CONSTRAINT user_roles_roles_check CHECK ((roles::text = ANY (ARRAY['MUSICIAN','EDITOR','DIRECTOR','PRODUCER','ACTOR','CINEMATOGRAPHER','VFX_ARTIST','WRITER']::text[])))
);

CREATE TABLE IF NOT EXISTS user_languages (
    user_id bigint NOT NULL REFERENCES users(id),
    languages character varying(255)
);

CREATE TABLE IF NOT EXISTS user_skills (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category character varying(255),
    level character varying(255),
    name character varying(255),
    user_id bigint NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content character varying(3000),
    created_at timestamp(6) without time zone,
    image_url character varying(255),
    author_id bigint NOT NULL REFERENCES users(id),
    is_project boolean,
    project_type character varying(255)
);

CREATE TABLE IF NOT EXISTS post_likes (
    post_id bigint NOT NULL REFERENCES posts(id),
    user_id bigint REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS portfolio_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category character varying(255),
    created_at timestamp(6) without time zone,
    description text,
    image_url character varying(255),
    title character varying(255),
    video_url character varying(255),
    user_id bigint NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content character varying(1000),
    created_at timestamp(6) without time zone,
    author_id bigint NOT NULL REFERENCES users(id),
    post_id bigint NOT NULL REFERENCES posts(id),
    candidate_status character varying(255),
    share_portfolio boolean,
    parent_comment_id bigint REFERENCES comments(id),
    portfolio_item_id bigint REFERENCES portfolio_items(id),
    is_read boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS connections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    responded_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    receiver_id bigint NOT NULL REFERENCES users(id),
    sender_id bigint NOT NULL REFERENCES users(id),
    UNIQUE (sender_id, receiver_id),
    CONSTRAINT connections_status_check CHECK ((status::text = ANY (ARRAY['PENDING','ACCEPTED','DECLINED','BLOCKED']::text[])))
);

CREATE TABLE IF NOT EXISTS messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content character varying(2000) NOT NULL,
    created_at timestamp(6) without time zone,
    is_read boolean NOT NULL,
    receiver_id bigint NOT NULL REFERENCES users(id),
    sender_id bigint NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    is_read boolean,
    message character varying(255) NOT NULL,
    reference_id bigint,
    reference_type character varying(255),
    type character varying(255) NOT NULL,
    recipient_id bigint NOT NULL REFERENCES users(id),
    sender_id bigint NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS company_pages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bio text,
    city character varying(255),
    country character varying(255),
    cover_url character varying(255),
    created_at timestamp(6) without time zone,
    follower_count integer,
    is_official boolean,
    is_verified boolean,
    logo_url character varying(255),
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL UNIQUE,
    type character varying(255),
    website character varying(255),
    created_by bigint NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS company_follows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    company_id bigint NOT NULL REFERENCES company_pages(id),
    user_id bigint NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expires_at timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL UNIQUE,
    used boolean NOT NULL,
    user_id bigint NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS email_verification_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expires_at timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL UNIQUE,
    used boolean NOT NULL,
    user_id bigint NOT NULL REFERENCES users(id)
);
